### ISSUE TITLE
The email notifications don't work

### ISSUE THREAD

**Issue by kanewinter** [QuantumObject/docker-nagios#7]
Currently throws:
[1466708216] wproc:   stderr line 01: sendmail: invalid option -- 's'
[1466708216] wproc:   stderr line 02: sendmail: invalid option -- 's'
[1466708216] wproc:   stderr line 03: sendmail: fatal: usage: sendmail [options]

Postfix sendmail is included instead of heirloom mail or something fully compatible.

**Comment by jamfwright** [comment]
I see this issue too, but think it is a postfix issue:

root@af3bf7bcf962:/# service postfix stop
 * Stopping Postfix Mail Transport Agent postfix
   ...done.

root@af3bf7bcf962:/# service postfix start
 * Starting Postfix Mail Transport Agent postfix
postfix/postfix-script: fatal: the Postfix mail system is already running
   ...fail!

root@af3bf7bcf962:/# echo "This is the body of the email" | mail -s "This is the subject line" user@test.com
bash: mail: command not found

**Comment by jamfwright** [comment]
To fix the sendmail issue I found this:
https://brandonwamboldt.ca/configure-nagios-to-use-sendmail-1188/

I am now getting service alerts.

**Comment by angelrr7702** [comment]
note for reference : 

/usr/local/nagios/etc/objects/commands.cfg

/usr/sbin/sendmail -vt  
/usr/sbin/sendmail -s   ==> invalid option   (default options)

**Comment by angelrr7702** [comment]
Hi,

 this specified error was fix in the last build ..

**Comment by jamfwright** [comment]
Thanks!
